
; BACK_COLOR = "#FFFFCC"では、tkinterで""#FFFFCC""になる

[PATH]
BACKUP_PATH = F:\\xampp_backup
UPLOAD_PATH = D:\\rekisi/walk/stamp
[GUI]
BACK_COLOR = #FFCC66
TEXT_COLOR = #FF3333
BUTTON_COLOR = #FF9933
BUTTON_COLOR2 = #FFCC99
TEXT_BOX_COLOR = #FFFFCC

